<?php
/*
* List Sub catgories template
*/
?>

<?php
    $object = new Mage_Catalog_Block_Navigation();
    $categoyrId = 2;
    $actualCategory = Mage::getModel('catalog/category')->load($categoyrId);
    $subCategories = explode(',', $actualCategory->getChildren()); ?>

    <div class="sub-cat-list">
    <h2>CATEGORIES</h2>
    <ul>
    <?php $i; foreach ($subCategories as $subCategoryId): $i++; ?>
        <?php 
        $category = Mage::getModel('catalog/category')->load($subCategoryId);
        if ($category->getIsActive() ): 
        ?>
        <li class="catItem">

            <?php if($category->getThumbnail()): ?>
                <a href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'. $category->getThumbnail(); ?>" alt=""  /></a>
            <?php endif; ?> 
            <div class="bottom">
            <h3><a href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><?php echo $category->getName(); ?></a></h3>

            <?php // show subs ?>
            <?php $newSubCategories = explode(',', $category->getChildren()); ?>
            <ul> 
                <?php foreach ($newSubCategories as $newSubCategoryId): ?>
                <?php $newCategory = Mage::getModel('catalog/category')->load($newSubCategoryId); ?>
                    <li class="subCat">
                    <a href="<?php echo $newCategory->getURL(); ?>" class="categoryLink" title="<?php echo $newCategory->getName(); ?>"><?php echo $newCategory->getName(); ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
            </div>
            <a class="viewAll" href="<?php echo $category->getURL(); ?>" title="<?php echo $category->getName(); ?>"><span>Check All Categories</span></a>
        </li>
        <?php endif; ?>
    <?php endforeach; ?> 
    </ul>
    </div>