<?php 
/**
 * Ultimate_creditcard extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ultimate
 * @package        Ultimate_creditcard
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Customer list template
 *
 * @category    Ultimate
 * @package     Ultimate_creditcard
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_customers = $this->getCustomers(); ?>
<div class="page-title customer-title">
    <h1><?php echo Mage::helper('ultimate_creditcard')->__('Customers') ?></h1>
</div>
<?php if ($_customers->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="customer-list-container">
    <?php foreach ($_customers as $_customer) : ?>
        <div class="customer-list-item">
            <a href="<?php echo $_customer->getCustomerUrl()?>">
                <?php echo $_customer->getCreditcardNumber();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('ultimate_creditcard')->__('There are no customers at this moment');?>
<?php endif;?>
