<?php
$cust_id = Mage::app()->getRequest()->getParam('id');
$cusgroup = Mage::getModel('customer/customer')->load(Mage::app()->getRequest()->getParam('id'))->getGroupId(); // get customer group id
$group = Mage::getModel('customer/group')->load($cusgroup); //Get customer Group name
$info = $this->getCustomerpayment();
$info['customer_pro_id'];
$info['customer_payment_id'];
$info['customer_address_id'];
$info['membership_id'];
$info['getmembership_type'];
$info['getamount'];
// calculate tax
$customerData = Mage::getModel('customer/customer')->load($cust_id);
$taxCalculation = Mage::getModel('tax/calculation')->setCustomer($customerData);
$address_id = $customerData->getDefaultBilling();
$address = Mage::getModel('customer/address')->load($address_id);
$region_id = $address->getRegionId();
// get additional services
$collection = Mage::getModel('membership/additionalservices')->getCollection();
?>

<table cellspacing="0" class="form-edit">
    <tr>
        <td class="payment-section">
            <div class="entry-edit-head">
                <h4 class="icon-head head-customer-address-list"><?php echo Mage::helper('customer')->__('Membership Information') ?></h4>
            </div>   
            <div class="fieldset">                              
                <input type="hidden" name="return_url" value="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/customer/edit/id', array('id' => Mage::app()->getRequest()->getParam('id'))) ?>" />
                <input type="hidden" name="customer_entity_id" value="<?php echo Mage::app()->getRequest()->getParam('id'); ?>" />
                <?php if ($cusgroup === '1') {//members group   ?>
                    <h4> Membership Status :<?php echo $group->getCode(); ?></h4>
                    <h4> Membership type - <?php echo $info['getmembership_type'] ?> </h4>
                    <h4> Membership amount - <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $info['getamount'] ?> </h4>
                    <?php
                    if ($region_id == '43') {
                        $request = $taxCalculation->getRateRequest($address, null, null);
                        $taxClassId = 2;
                        $taxRate = $taxCalculation->getRate($request->setProductClassId($taxClassId));
                        $taxval = $taxRate / 100;
                        $taxable_amount111 = $info['getamount'] * $taxval;
                        $taxable_amount = number_format($taxable_amount111, 2);
                        $mem_amount111 = $info['getamount'] + $taxable_amount;
                        $mem_amount = number_format($mem_amount111, 2)
                        ?>
                        <h4> Tax Rate - <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $taxable_amount ?> </h4>
                        <h4> Total membership amount - <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $mem_amount ?> </h4>
                        <input type="hidden" id="mem_choose_price" value="<?php echo $mem_amount ?>"/>
                    <?php } else { ?>
                        <input type="hidden" id="mem_choose_price" value="<?php echo $info['getamount'] ?>"/>
                    <?php } ?>
                    <h4> Number of items in MyCloset - <?php
                        echo $userid = Mage::getSingleton('customer/session')->getId();
                        $products = Mage::getModel('catalog/product')
                                ->getCollection()
                                ->addAttributeToSelect('entity_id')
                                ->addAttributeToFilter('status', 1)
                                ->addAttributeToFilter('customer_id', Mage::app()->getRequest()->getParam('id'))
                                ->addAttributeToFilter('visibility', 4);
                        echo $myclosetcount = $products->count();
                        ?></h4>
                        <input type="hidden" id="myclosetcount" value="<?php echo $myclosetcount; ?>" name="myclosetcount" />
                        <input type="text" id="constantamount" value="3" name="constantamount"/>
                    <input type="checkbox" checked="checked" id="add5" value="<?php
                    if ($region_id == '43') {
                        echo $mem_amount;
                    } else {
                        echo $info['getamount'];
                    }
                    ?>"  onclick="UpdateCost();"> &nbsp;Include membership charge for payment
                    
                    
                    
                       <?php } elseif ($cusgroup === '4') {//Waiting List group    ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } elseif ($cusgroup === '15') {//Non paid member groop   ?>
                    <h4> <label>Membership Status</label>: <?php echo $group->getCode(); ?></h4>
                <?php } elseif ($cusgroup === '5') {//membership closed group    ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } elseif ($cusgroup === '6') {// notice period group    ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } else { ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } ?>       
                <input type="hidden" name="mem_type_name" value="<?php echo $info['getmembership_type'] ?>"/>
                <input type="hidden" name="customer_pro_id" value="<?php echo $info['customer_pro_id'] ?>"/>
                <input type="hidden" name="customer_payment_id" value="<?php echo $info['customer_payment_id'] ?>"/>
                <input type="hidden" name="customer_address_id" value="<?php echo $info['customer_address_id'] ?>"/>
                <input type="hidden" id="finalamount" value="<?php echo array_sum($price); ?>" name="amount" />                
            </div>
        </td>
    </tr>
</table>
<div class="payment-sections">
    <div id="customer_info_tabs_Membership payments_content" style="width: 38%; float: left; padding-right: 22px;">
        <table class="form-edit" cellspacing="0">
            <tbody><tr>
                    <td class="payment-section">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-customer-address-list">Additional services</h4>
                        </div>   
                        <div class="fieldset">
                            <?php
                            $i = 0;
                            foreach ($collection as $services) {
                                $service = Mage::getModel('membership/additionalservices')->load($services->getId());
                                ?>
                                <input type="checkbox" id="add<?php echo $i ?>" name="<?php echo $service->getServiceName(); ?>" value="<?php echo $service->getAmount(); ?>" onclick="UpdateCost()" ><label ><?php echo $service->getServiceName(); ?></label></br>
                                <?php
                                $i++;
                            }
                            ?>
                            <div id="additional-amt" style="border: 1px solid #d6d6d6;padding: 10px;margin: 10px 0;">
                                <b>Additional payments</b> <br>
                                <textarea rows="3" cols="50" name="comment" style="resize: none;">Enter your comments here</textarea><br>
                                Amount for the service<br><input type="text" id="addvalue" value="0" style="width: 30px;" onkeyup="UpdateCost()" /><br>
                            </div>
                            <div id="price"><h4>Total cost for additional services $ <span id="priceholder">0</span></h4></div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <input type="hidden" name="planup" id="planup" value="0">
    <div id="customer_info_tabs_Membership payments_conten" style="width: 59%; float: right;">
        <table class="form-edit" cellspacing="0">
            <tbody><tr>
                    <td class="payment-section">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-customer-address-list">Services used by the customer</h4>
                        </div>   
                        <div class="fieldset">
                            <table class="data" id="customer_orders_grid_table" cellspacing="0">
                                <colgroup><col width="200">
                                    <col width="200">
                                    <col width="100">
                                </colgroup><thead style="border: 1px solid black; background: #d6d6d6;">
                                    <tr class="headings">
                                        <th><span class="nobr"><span class="sort-title">Order Id</span></span></th>
                                        <th><span class="nobr"><span class="sort-title">Date</span></span></th>
                                        <th><span class="nobr"><span class="sort-title">Amount</span></span></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
//                  
                                    echo 'customerid=' . $customerid = Mage::app()->getRequest()->getParam('id');
                                    $orders = Mage::getResourceModel('sales/order_collection')
                                            ->addFieldToSelect('*')
                                            ->addFieldToFilter('customer_id', $customerid)
//        ->addFieldToFilter('state', array('in' => Mage::getSingleton('sales/order_config')->getVisibleOnFrontStates()))
                                            ->setOrder('created_at', 'desc');
//     $this->setOrders($orders); 
                                    foreach ($orders as $order):
                                       // echo '<pre>';
                                      //  print_r($order);
                                        ?>
                                        <tr>
                                            <th><a href="http://localhost/mgn/magento/index.php/admin/sales_order/view/order_id/<?php echo$order->getEntityId();?>/key/"><?php echo $order->getRealOrderId(); ?></a></th>
                                            <th><?php echo $order->getCreatedAtStoreDate(); ?></th>
                                            <th>
                                                <label>shipping :</label><?php echo  $order->formatPrice($order->getGrandTotal()); ?>
                                                <label>Product :</label><?php echo  $order->formatPrice($order->getGrandTotal()); ?>
                                            
                                            </th>
                                        </tr>
                                        <?php
                                    endforeach;
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <h5>Total amount for services used :<?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . array_sum(); ?>
        </h5>
        <input id="servicesum" type="hidden" value="<?php echo array_sum($price); ?>"/>
    </div>
</div>
<div class="sss" style="float: left ; width: 100%;">
    <h2 id="final">Total amount to be paid : 
        <span id="currency" style="color: #ff0033;">
            <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol(); ?>
        </span><span id="finalpricedisplay" style="color: #ff0033;">
            <?php
            //for New York region check ;43->New York
            if ($region_id == '43') {
                echo $mem_amount;
            } else {
                echo $info['getamount'];
            }
            ?>
        </span>
    </h2>
    <button type='submit' class="scalable" value='Submit' onclick='this.form.action = "<?php echo Mage::getBaseUrl(); ?>membership/payment/payme/";' value="Submit">Pay for the customer</button>
</div>
<script type="text/javascript">
    function Getplan(mem) {
        document.getElementById("planup").value = mem;
    }

    function UpdateCost() {
        var sum = 0;
        var input, elem, element,element1,element3, memsum = 0;
        element = document.getElementById('add5');
        element1 = document.getElementById('constantamount');
        element3 = document.getElementById('myclosetcount');
           var constantamt = element1.value;
        if(element3 >=50){
            constantamt =constantamt*element3;
        }else{
            constantamt;
        }
        if (element.checked == true) {
            memsum = element.value;
        }
        else {
            memsum = 0;
        }
     
        var parameters = "name=" + sum;

        for (i = 0; i < 6; i++) {
            input = 'add' + i;
            elem = document.getElementById(input);

            if (elem.checked == true) {

                sum += Number(elem.value);

                var xmlhttp;
                if (window.XMLHttpRequest)
                {// code for IE7+, Firefox, Chrome, Opera, Safari
                    xmlhttp = new XMLHttpRequest();
                }
                else
                {// code for IE6, IE5
                    xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                }
                xmlhttp.onreadystatechange = function ()
                {
                    if (xmlhttp.readyState == 4 && xmlhttp.status == 200)
                    {

                        //                         
                    }
                }
                xmlhttp.open("POST", "<?php echo Mage::getBaseUrl(); ?>membership/payment/payme/", true);
                xmlhttp.send(parameters);

            }
        }
        sumtot =  parseFloat(constantamt)+ parseFloat(sum) + parseFloat(document.getElementById('servicesum').value) + parseFloat(document.getElementById('addvalue').value);
        document.getElementById("priceholder").innerHTML = constantamt + sum + parseFloat(document.getElementById('addvalue').value) - parseFloat(memsum);
        document.getElementById("finalamount").value = sumtot.toFixed(2);
        document.getElementById("finalpricedisplay").innerHTML = sumtot.toFixed(2);
    }
</script>

<?php if ($this->getRequest()->getParam('q') == success): ?>

    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Payment processed successfully with transaction id <?php echo $this->getRequest()->getParam('tranid'); ?></span></li></ul></li></ul>');
        });
    </script>
<?php elseif ($this->getRequest()->getParam('q') == error): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="error-msg"><ul><li><span>Payment process error</span></li></ul></li></ul>');
        });
    </script>
<?php elseif ($this->getRequest()->getParam('q') == act): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Membership activated successfully</span></li></ul></li></ul>');
        });
    </script>

<?php elseif ($this->getRequest()->getParam('q') == deact): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="error-msg"><ul><li><span>Membership deactivated </span></li></ul></li></ul>');
        });
    </script>

<?php elseif ($this->getRequest()->getParam('q') == saved): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Membership saved successfully</span></li></ul></li></ul>');
        });
    </script>

<?php endif; ?>
