<?php
$cust_id = Mage::app()->getRequest()->getParam('id');
$cusgroup = Mage::getModel('customer/customer')->load(Mage::app()->getRequest()->getParam('id'))->getGroupId(); // get customer group id
$group = Mage::getModel('customer/group')->load($cusgroup); //Get customer Group name
$info = $this->getCustomerpayment();
$info['customer_pro_id'];
$info['customer_payment_id'];
$info['customer_address_id'];
$info['membership_id'];
$info['getmembership_type'];
$info['getamount'];
$info['storage_amt'];
$info['min_storage'];
// calculate tax
$customerData = Mage::getModel('customer/customer')->load($cust_id);
$taxCalculation = Mage::getModel('tax/calculation')->setCustomer($customerData);
$address_id = $customerData->getDefaultBilling();
$address = Mage::getModel('customer/address')->load($address_id);
$region_id = $address->getRegionId();
// get additional services
$collection = Mage::getModel('membership/additionalservices')->getCollection();
$userid = Mage::getSingleton('customer/session')->getId();
$products = Mage::getModel('catalog/product')
        ->getCollection()
        ->addAttributeToSelect('entity_id')
        ->addAttributeToFilter('status', 1)
        ->addAttributeToFilter('customer_id', Mage::app()->getRequest()->getParam('id'))
        ->addAttributeToFilter('visibility', 4);
$myclosetcount = $products->count();
if ($myclosetcount > $info['min_storage']) {
    $storageAmount = $myclosetcount * $info['storage_amt'];
} else {
    $storageAmount = $info['min_storage'] * $info['storage_amt'];
}
?>
<!--<form action="<?php // echo Mage::getBaseUrl();   ?>membership/payment/payme/" method="post" id="payme_form" >-->

<table cellspacing="0" class="form-edit">
    <tr>
        <td class="payment-section" >
            <div class="entry-edit-head">
                <h4 class="icon-head head-customer-address-list"><?php echo Mage::helper('customer')->__('Membership Information') ?></h4>
                <input type="hidden" name="return_url" value="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/customer/edit/id', array('id' => Mage::app()->getRequest()->getParam('id'))) ?>" />
                <input type="hidden" name="customer_entity_id" value="<?php echo Mage::app()->getRequest()->getParam('id'); ?>" />
            </div>   
            <div class="fieldset">                              
                <?php if ($cusgroup === '1') {//members group    ?>
                    <label>Membership Status:</label>&nbsp;<?php echo $group->getCode(); ?><br>
                    <label>Membership Type:</label>&nbsp;<?php echo $info['getmembership_type'] ?> <br>
                    <label>Membership Amount:</label>&nbsp;<?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $info['getamount'] ?> <br>
                    <?php
                    if ($region_id == '43') {
                        $request = $taxCalculation->getRateRequest($address, null, null);
                        $taxClassId = 2;
                        $taxRate = $taxCalculation->getRate($request->setProductClassId($taxClassId));
                        $taxval = $taxRate / 100;
                        $taxable_amount111 = $info['getamount'] * $taxval;
                        $taxable_amount = number_format($taxable_amount111, 2);
                        $mem_amount111 = $info['getamount'] + $taxable_amount;
                        $mem_amount = number_format($mem_amount111, 2)
                        ?>
                        <label> Tax Rate:</label>&nbsp;<?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $taxable_amount ?> <br>
                        <label> Total Membership Amount:</label>&nbsp;<?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $mem_amount ?><br> 
                        <input type="hidden" id="mem_choose_price" value="<?php echo $mem_amount ?>"/>
                    <?php } else { ?>
                        <input type="hidden" id="mem_choose_price" value="<?php echo $info['getamount'] ?>"/>
                    <?php } ?>
                    <label>Number of Items in MyCloset:</label> <?php echo $myclosetcount; ?></br>                                    
                    <label>Storage Amount:</label> $<?php echo $storageAmount; ?></br>
                    <input type="hidden" id="items_amt" value="<?php echo $info['storage_amt']; ?>"/>
                    <input type="checkbox" checked="checked" id="add5" name="include_membershipcharge" value="<?php
                    if ($region_id == '43') {
                        echo $mem_amount;
                    } else {
                        echo $info['getamount'];
                    }
                    ?>"  onclick="UpdateCost();"> &nbsp;Include Membership Charge for Payment <br>

                    <input type="checkbox" checked="checked" id="storageitems" value="<?php echo $storageAmount ?>"  onclick="UpdateCost();"> &nbsp;Include Storage Charge for Payment

                <?php } elseif ($cusgroup === '4') {//Waiting List group     ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } elseif ($cusgroup === '15') {//Non paid member groop   ?>
                    <h4> <label>Membership Status</label>: <?php echo $group->getCode(); ?></h4>
                <?php } elseif ($cusgroup === '5') {//membership closed group    ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } elseif ($cusgroup === '6') {// notice period group    ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } else { ?>
                    <h4 style="color: #DF280A;"> <?php echo $group->getCode(); ?></h4>
                <?php } ?>       
                <input type="hidden" name="mem_type_name" value="<?php echo $info['getmembership_type'] ?>"/>
                <input type="hidden" name="customer_pro_id" value="<?php echo $info['customer_pro_id'] ?>"/>
                <input type="hidden" name="customer_payment_id" value="<?php echo $info['customer_payment_id'] ?>"/>
                <input type="hidden" name="customer_address_id" value="<?php echo $info['customer_address_id'] ?>"/>

            </div>
        </td>


    </tr>
</table>
<div class="payment-sections">
    <div id="customer_info_tabs_Membership payments_content" style="width: 38%; float: left; padding-right: 22px;">
        <table class="form-edit" cellspacing="0">
            <tbody><tr>
                    <td class="payment-section">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-customer-address-list">Additional Services</h4>
                        </div>   
                        <div class="fieldset">
                            <?php
                            $i = 0;
                            foreach ($collection as $services) {
                                $service = Mage::getModel('membership/additionalservices')->load($services->getId());
                                ?>
                            <input type="checkbox" id="add<?php echo $i ?>" name="<?php echo $service->getServiceName(); ?>" value="<?php echo $service->getAmount(); ?>" onclick="UpdateCost()" >&nbsp;<label ><?php echo $service->getServiceName(); ?></label></br>
                                <?php
                                $i++;
                            }
                            ?>
                            <div id="additional-amt" style="border: 1px solid #d6d6d6;padding: 10px;margin: 10px 0;">
                                <b>Additional Payments</b> <br>
                                <textarea rows="3" cols="50" name="comment" style="resize: none;">Enter your comments here</textarea><br>
                                Amount for the Service<br><input type="text" id="addvalue" value="0" style="width: 30px;" onkeyup="UpdateCost()" /><br>
                            </div>
                            <div id="price"><h4>Total Cost for Additional Services $<span id="priceholder">0</span></h4></div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <input type="hidden" name="planup" id="planup" value="0">
    <div id="customer_info_tabs_Membership payments_conten" style="width: 59%; float: right;">
        <table class="form-edit" cellspacing="0">
            <tbody><tr>
                    <td class="payment-section">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-customer-address-list">Services Used by the Customer</h4>
                        </div>   
                        <div class="fieldset">
                            <table class="data" id="customer_orders_grid_table" cellspacing="0">
                                <colgroup>
                                    <col width="100">
                                    <col width="200">
                                    <col width="200">
                                    <col width="100">
                                    <col width="100">
                                    <col width="100">

                                </colgroup>
                                <thead style=" background: #d6d6d6;">
                                    <tr class="headings">
                                        <th><span class="nobr"><span class="sort-title"></span></span></th>
                                        <th><span class="nobr"><span class="sort-title">Order ID</span></span></th>
                                        <th><span class="nobr"><span class="sort-title">Place Order On</span></span></th>
                                        <th><span class="nobr"><span class="sort-title">Shipping</span></span></th>
                                        <th><span class="nobr"><span class="sort-title">Product  </span></span></th>
                                        <th><span class="nobr"><span class="sort-title">  Total</span></span></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
//                  
                                    $customerid = Mage::app()->getRequest()->getParam('id');
                                    $orders = Mage::getResourceModel('sales/order_collection')
                                            ->addFieldToSelect('*')
                                            ->addFieldToFilter('customer_id', $customerid)
                                            ->addFieldToFilter('status', 'Processing')
                                            ->setOrder('created_at', 'asc');
                                    $sum1 = 0;
                                    $i = 0;
                                    foreach ($orders as $order):
                                        ?>

                                    <input type="hidden" value="<?php echo $order->getRealOrderId(); ?>" name="order_id[<?php echo $order['increment_id']; ?>]" />
                                    <?php
//                                    $i++;
//                                    if ($i == 1 && $info['membership_id'] == '3') {
//                                        ?>
<!--                                        <tr style="text-decoration: line-through">
                                            <th></th>
                                            <th><a href="<?php //echo Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view/order_id/', array('order_id' => $order->getEntityId())); ?>"><?php echo $order->getRealOrderId(); ?></a></th>
                                            <th><?php //echo $order->getCreatedAtStoreDate(); ?></th>
                                            <th><?php// echo $order->formatPrice($order->getShippingAmount()) ?></th>
                                            <th><?php //echo $order->formatPrice($order->getSubtotalInclTax()) ?></th>                                                                                                                                          
                                            <th><?php// echo $order->formatPrice($order->getGrandTotal()) ?></th> 
                                        </tr>  -->
                                        <?php
//                                        continue;
//                                    }
                                    ?>
                                    <tr>
                                        <?php ?>
                                        <th> <input type="checkbox" checked="checked" class="ordercheck"  value="<?php echo $order->getGrandTotal(); ?>" onclick="UpdateCost()"/> </th>
                                        <th><a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view/order_id/', array('order_id' => $order->getEntityId())); ?>"><?php echo $order->getRealOrderId(); ?></a></th>
                                        <th><?php echo $order->getCreatedAtStoreDate(); ?></th>
                                        <th><?php echo $order->formatPrice($order->getShippingAmount()) ?></th>
                                        <th><?php echo $order->formatPrice($order->getSubtotalInclTax()) ?></th>                                                                                                                                          
                                        <th><?php echo $order->formatPrice($order->getGrandTotal()) ?></th>  
                                        <?php ?>
                                    </tr> 

                                    <?php
                                    $sum1 = $sum1 + $order->getGrandTotal();
                                endforeach;
                                ?>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <h5>  Total Amount for Services Used:&nbsp;<?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() ?><span id="ordersum"><?php echo $sum1 ?></span></h5>
        <input id="servicesum" type="hidden" value="<?php echo $sum1; ?>" name="servicesum"/>
        <input type="hidden" id="storeamt" value="<?php echo $storageAmount; ?>" name="storeamt"/>
        <input type="hidden" id="myclosetcount" value="<?php echo $myclosetcount; ?>" name="myclosetcount"/>
    </div>
</div>
<div class="sss" style="float: left ; width: 100%;">
    <h2 id="final">Total amount to be paid: 
        <span id="currency" style="color: #ff0033;">
            <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol(); ?>
        </span><span id="finalpricedisplay" style="color: #ff0033;">
            <?php
            //for New York region check ;43->New York
            if ($region_id == '43') {
                echo $grandtotal = $mem_amount + $sum1 + $storageAmount;
            } else {
                echo $grandtotal = $info['getamount'] + $sum1 + $storageAmount;
            }
            ?>
        </span>

    </h2>
    <input type="hidden" id="finalamount" value="<?php echo $grandtotal; ?>" name="amount" />   
    <button type="submit" class="scalable"  onclick="this.form.action = '<?php echo Mage::getBaseUrl(); ?>membership/payment/payme/'" value="Submit">Pay for the Customer</button>
</div>
<!--</form>-->
<script type="text/javascript">
    function Getplan(mem) {
        document.getElementById("planup").value = mem;
    }

    function UpdateCost() {
        var sum = 0;
        var sum12 = 0;
        var input, elem, element, itemsamt, storageitems, memsum = 0, min_storage;
        element = document.getElementById('add5');
        storageitems = document.getElementById('storageitems');
        var addvalue = document.getElementById('addvalue').value;
        if (addvalue == "") {
            addvalue = 0;
        }

        if (storageitems.checked == true) {
            itemsamt = document.getElementById('storeamt').value;

        } else {
            itemsamt = 0;
        }
        if (element.checked == true) {
            memsum = element.value;
        }
        else {
            memsum = 0;
        }
        var ordercheck = document.getElementsByClassName('ordercheck');

        count = 0;
//grandtotal=0;
        for (var i = 0; i < ordercheck.length; i++) {
            element12 = ordercheck[i];
            if (element12.checked) {

                sum12 += Number(element12.value);
                count++;
            }
        }



        var parameters = "name=" + sum;

        for (i = 0; i < 6; i++) {
            input = 'add' + i;
            elem = document.getElementById(input);

            if (elem.checked == true) {

                sum += Number(elem.value);

                var xmlhttp;
                if (window.XMLHttpRequest)
                {// code for IE7+, Firefox, Chrome, Opera, Safari
                    xmlhttp = new XMLHttpRequest();
                }
                else
                {// code for IE6, IE5
                    xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
                }
                xmlhttp.onreadystatechange = function ()
                {
                    if (xmlhttp.readyState == 4 && xmlhttp.status == 200)
                    {

                        //                         
                    }
                }
                xmlhttp.open("POST", "<?php echo Mage::getBaseUrl(); ?>membership/payment/payme/", true);
                xmlhttp.send(parameters);

            }
        }
        document.getElementById("ordersum").innerHTML = sum12;
        document.getElementById("servicesum").value = sum12;
        sumtot = parseFloat(itemsamt) + parseFloat(sum) + parseFloat(sum12) + parseFloat(addvalue);
        document.getElementById("priceholder").innerHTML = sum + parseFloat(addvalue) - parseFloat(memsum);
        document.getElementById("finalamount").value = sumtot.toFixed(2);
        document.getElementById("finalpricedisplay").innerHTML = sumtot.toFixed(2);
    }
</script>

<?php if ($this->getRequest()->getParam('q') == success): ?>

    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Payment processed successfully with transaction id <?php echo $this->getRequest()->getParam('tranid'); ?></span></li></ul></li></ul>');
        });
    </script>
<?php elseif ($this->getRequest()->getParam('q') == error): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="error-msg"><ul><li><span>Payment process error</span></li></ul></li></ul>');
        });
    </script>
<?php elseif ($this->getRequest()->getParam('q') == act): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Membership activated successfully</span></li></ul></li></ul>');
        });
    </script>

<?php elseif ($this->getRequest()->getParam('q') == deact): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="error-msg"><ul><li><span>Membership deactivated </span></li></ul></li></ul>');
        });
    </script>

<?php elseif ($this->getRequest()->getParam('q') == saved): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");

            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Membership saved successfully</span></li></ul></li></ul>');
        });
    </script>

<?php endif; ?>
