


<table cellspacing="0" class="form-edit">
    <tr>
        <td class="payment-section">
            <div class="entry-edit-head">
                <h4 class="icon-head head-customer-address-list"><?php echo Mage::helper('customer')->__('Customer Payments') ?></h4>
            </div>   

            <div class="fieldset">
                <input type="hidden" name="return_url" value="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/customer/edit/id', array('id' => Mage::registry('current_customer')['entity_id'])) ?>" />
                <input type="hidden" name="customer_entity_id" value="<?php echo Mage::registry('current_customer')['entity_id']; ?>" />
                <?php
                $pay = explode('-', $this->getCustomerpayment());
                ?>
                <h4> Membership type - <?php echo $pay['4'] ?></h4><br>
                Amount paid for the current plan - <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '' . $pay['3'] ?></h4><br>

                <input type="radio" name="mem_plan" id="mem_plan" value="<?php echo $pay['3'] ?>" onclick="Getplan(this.value);
                        UpdateCost();" checked>Renew current membership plan
                <br>
                <input type="radio" name="mem_plan" id="mem_plan" onclick="Getplan(this.value);
                        UpdateCost();" value="180">Upgrade membership plan to Endless closet
                <br>
                <input type="radio" name="mem_plan" id="mem_plan" value="150" onclick="Getplan(this.value);
                        UpdateCost();">Upgrade membership plan to Standard closet




   <!--                <form action="<?php echo Mage::getBaseUrl(); ?>membership/payment/payme" type="post">-->

                <input type="hidden" name="customer_pro_id" value="<?php echo $pay['0'] ?>"/>
                <input type="hidden" name="customer_payment_id" value="<?php echo $pay['1'] ?>"/>
                <input type="hidden" name="customer_address_id" value="<?php echo $pay['2'] ?>"/>
                <input type="hidden" id="finalamount" value="<?php echo array_sum($price); ?>" name="amount" />

                <!--                <button type="Submit" class="scalable" value="Pay for this customer" onclick="setLocation('http://localhost/bridge-member/index.php/membership/payment/payme/')">Pay for the customer</button>-->

            </div>
        </td>
    </tr>

</table>



<script type="text/javascript">
    function Getplan(mem) {
        document.getElementById("planup").value = mem;
    }
</script>

<script type="text/javascript">


    function UpdateCost() {
        var sum = 0;
        var input, elem;
        for (i = 0; i < 5; i++) {
            input = 'add' + i;
            elem = document.getElementById(input);
            if (elem.checked == true) {
                sum += Number(elem.value);
            }
        }
        sumtot = parseFloat(sum) + parseFloat(document.getElementById('servicesum').value) + parseFloat(document.getElementById('planup').value);
        document.getElementById("priceholder").innerHTML = sum.toFixed(2);
        document.getElementById("finalamount").value = sumtot.toFixed(2);
        document.getElementById("finalpricedisplay").innerHTML = sumtot.toFixed(2);

    }
</script>
<div class="payment-sections">
    <div id="customer_info_tabs_Membership payments_content" style="width: 38%; float: left; padding-right: 22px;">
        <table class="form-edit" cellspacing="0">
            <tbody><tr>
                    <td class="payment-section">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-customer-address-list">Additional services</h4>
                        </div>   

                        <div class="fieldset">
                            <input type="checkbox" id='add0' value="5"  onclick="UpdateCost()">Third party storage<br>
                            <input type="checkbox" id='add1' value="10" onclick="UpdateCost()">Shipping charges<br>
                            <input type="checkbox" id='add2' value="15" onclick="UpdateCost()">Delivery charges<br>
                            <input type="checkbox" id='add3' value="20" onclick="UpdateCost()">Secondary fees<br>
                            <input type="checkbox" id='add4' value="25" onclick="UpdateCost()">Parking fees<br>
                            <div id="price"><h4>Total cost for additional services $ <span id="priceholder">0</span></h4></div>
                        </div>
                    </td>
                </tr>

            </tbody>
        </table>

    </div>

    <input type="text" name="planup" id="planup" value="">

    <div id="customer_info_tabs_Membership payments_conten" style="width: 59%; float: right;">
        <table class="form-edit" cellspacing="0">
            <tbody><tr>
                    <td class="payment-section">
                        <div class="entry-edit-head">
                            <h4 class="icon-head head-customer-address-list">Services used by the customer</h4>
                        </div>   

                        <div class="fieldset">
                            <table class="data" id="customer_orders_grid_table" cellspacing="0">
                                <colgroup><col width="200">
                                    <col width="200">
                                    <col width="100">
                                </colgroup><thead>
                                    <tr class="headings">
                                        <th><span class="nobr"><a href="#" name="increment_id" title="asc" class="not-sort"><span class="sort-title">Service name</span></a></span></th>
                                        <th><span class="nobr"><a href="#" name="created_at" title="asc" class="sort-arrow-desc"><span class="sort-title">Date</span></a></span></th>
                                        <th><span class="nobr"><a href="#" name="billing_name" title="asc" class="not-sort"><span class="sort-title">Amount</span></a></span></th>

                                    </tr>

                                </thead>

                                <tbody>
                                    <?php
                                    $services = $this->getChosenservices();
                                    $price = array_column($services, 'amount');

                                    foreach ($services as $chosen) {
                                        ?>

                                        <tr>
                                            <th>   <?php echo $chosen[servicename]; ?></th>
                                            <th>   <?php echo $chosen[timestamp]; ?></th>
                                            <th>   <?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . $chosen[amount]; ?></th>
                                        </tr>
                                        <?php echo array_sum($chosen[amount]); ?>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>



        <h5>Total amount for services used :<?php echo Mage::app()->getLocale()->currency($currency_code)->getSymbol() . '&nbsp;' . array_sum($price); ?>

        </h5>

        <input id="servicesum" type="hidden" value="<?php echo array_sum($price); ?>"/>



    </div>
</div>


<div class="sss">
    <h3 id="final">Total amount to be paid :$ <span id="finalpricedisplay"><?php echo array_sum($price); ?></span></h3>
    <button type='submit' class="scalable" value='Submit' onclick='this.form.action = "<?php echo Mage::getBaseUrl(); ?>membership/payment/payme/";' value="Submit">Pay for the customer</button>
</div>









<?php if ($this->getRequest()->getParam('q') == success): ?>

    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");
            //$("price_change").update = response;
            node.update('<ul class="messages"><li class="success-msg"><ul><li><span>Payment processed successfully with transaction id <?php echo $this->getRequest()->getParam('tranid'); ?></span></li></ul></li></ul>');
        });
    </script>

<?php elseif ($this->getRequest()->getParam('q') == error): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function () {
            node = $("messages");
            //$("price_change").update = response;
            node.update('<ul class="messages"><li class="error-msg"><ul><li><span>Payment process error</span></li></ul></li></ul>');
        });
    </script>
<?php endif; ?>
