
<?php
session_start();
$current_cat = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$path = $current_cat->getPath();
$ids = explode('/', $path);
if (isset($ids[2])) {
    $topParent = $ids[2];
}
foreach ($this->getItems() as $_item):
    if ($_item->getCount() > 0) {
        if ($topParent != 16) {
            if (($this->getName() == "Price")) {
                ?>
                <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>" > <input type="checkbox"/><?php echo $_item->getLabel() ?></a>                  
                <?php
            }
        } else {
            if ($this->getName() == "Color") {
                if ($_item->getLabel() == "Multi"):
                    ?>
                    <!--fo multi color box-->
                    <a  title="<?php echo $_item->getLabel() ?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>"> </a>                                   
                <?php else: ?>
                    <a style="background: <?php echo $_item->getLabel() ?>" title="<?php echo $_item->getLabel() ?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>"> </a>                                   
                <?php endif; ?>
            <?php } else { ?>
                    <a style="background: <?php echo $_item->getLabel() ?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>" ><?php echo $_item->getLabel() ?></a>   
                <?php
            }
        }
    } else {
        echo $_item->getLabel();
    } endforeach;
?>





