<?php
session_start();
   $catalogsearch = Mage::app()->getRequest()->getModuleName();
$current_cat = Mage::getSingleton('catalog/layer')->getCurrentCategory();
$path = $current_cat->getPath();
$ids = explode('/', $path);
if (isset($ids[2])) {
    $topParent = $ids[2];
}
foreach ($this->getItems() as $_item):
    if ($_item->getCount() > 0) {
        if ($topParent != 16 && $catalogsearch != 'catalogsearch') {
            if (($this->getName() == "Price")) {
                ?>
                <a class="cat_01" href="<?php echo $this->urlEscape($_item->getUrl()) ?>" > 
                <label class="checkbox_01">
                    <input type="checkbox"/>
                    <div class="cstmChk"></div>
                    <div class="checkbox_values"><?php echo $_item->getLabel() ?></div>
                </label>
                </a> 

               
                <?php
            }
        } else {
            if ($this->getName() == "Color") {
                if ($_item->getLabel() == "Multi"):
                    ?>
                    <!--fo multi color box-->
                    <a  title="<?php echo $_item->getLabel() ?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>"> </a>                                   
                <?php else: ?>
                    <a style="background: <?php echo $_item->getLabel() ?>" title="<?php echo $_item->getLabel() ?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>"> </a>                                   
                <?php endif; ?>
            <?php } else { ?>
                <a style="background: <?php echo $_item->getLabel() ?>" href="<?php echo $this->urlEscape($_item->getUrl()) ?>" ><?php echo $_item->getLabel() ?></a>   
                <?php
            }
        }
    } else {
        echo $_item->getLabel();
    } endforeach;
?>
