
<div class='fieldset'>
    <h2 class="legend">Make Payment</h2>
    

<?php echo Mage::getSingleton('customer/session')->getMemId();?>
    

    <form method="post" action="<?php echo Mage::getBaseUrl(); ?>membership/payment/authorizepayment/">

        <div class="form-list">
            <input type="hidden" name="mem_type" value="<?php echo $exp[1]; ?>" />
            <input type="hidden" name="amt" value="<?php echo $amount; ?>" />
            <div>
                <label for="card_number">Credit Card Number</label>
                <div class="input-box">
                    <input type="text" class="input-text"  name="x_card_num" value=""></input>
                </div>
            </div>

            <div>       
                <label for="exp">Card Expiry date</label><br>

<!--                    <input type="text" class="input-text" size="4" name="x_exp_date" value=""></input>-->
                <select name="card_exp_year" style="width: 10%">
                    <?php
                    for ($ye = date("Y"); $ye <= date("Y") + 20; $ye++) {
                        echo "<option value='$ye'>$ye</option>";
                    }
                    ?> 

                </select> 

                <select name="card_exp_month" style="width:7%;">
                    <?php
                    for ($mo = 1; $mo <= 31; $mo++)
                        echo "<option value='$mo'>$mo</option>";
                    ?>
                </select>

            </div>
            <div>
                <label for="CVV">CVV</label>
                <div class="input-box">
                    <input type="text" class="input-text" size="4" name="x_card_code" value=""></input>
                </div>
            </div>


            <div class="fields">
                <div class="field">
                    <label for="First Name">First Name</label>
                    <div class="input-box">
                        <input type="text" class="input-text" size="15" name="x_first_name" value="<?php echo Mage::getSingleton('customer/session')->getMemFname(); ?>" readonly></input>

                    </div>
                </div>
                <div class="field">
                    <label for="Last Name">Last Name</label>

                    <div class="input-box">
                        <input type="text" class="input-text" size="14" name="x_last_name" value="<?php echo Mage::getSingleton('customer/session')->getMemLname(); ?>" readonly></input>

                    </div>
                </div>
            </div>

        </div>

        <div class="buttons-set">

            <button type="submit" title="Submit" class="button"><span><span>Submit</span></span></button>
        </div>
    </form>






</div>
<script type="text/javascript">
    function GetPrice(memid)
    {

        new Ajax.Request('<?php echo Mage::getBaseUrl() . "membership/payment/Getprice?memid=" ?>' + memid,
                {
                    method: "get",
                    onSuccess: function (transport) {
                        var response = transport.responseText || "no response text";
                        node = $("price_change");
                        //$("price_change").update = response;
                        node.update(response);

                    },
                    onFailure: function () {
                        alert("Something went wrong...")
                    }
                });


    }
</script>








<div class="buttons-set">
    <p class="back-link"><a onclick="goBack()" class="back-link"><small>&laquo;Back</small></a></p>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>