
<div class='fieldset'>
    <h2 class="legend"></h2>
    <?php
    $membership = $this->getMembershipdetails();

    $var = $this->getSettings();
    $gateurl = $var['a'];
    $api_login_id = $var['b'];
    $transaction_key = $var['d'];
    $amount = $membership['membership_price']; // membership amount
    $mem_id = $membership['membership_id']; // membership id  
    $group_id = $membership['customer_group']; // groupid 
    $customer_email = $membership['customer_email']; // emailid
    $customer_custtele = $membership['customer_custtele']; // customer telephone
    $cust_id = $membership['customer_id']; // customer id
    // test tax
    $customerData = Mage::getModel('customer/customer')->load($cust_id);
    $taxCalculation = Mage::getModel('tax/calculation')->setCustomer($customerData);
    $address_id = $customerData->getDefaultShipping();
    $address = Mage::getModel('customer/address')->load($address_id);
// $shippingId is the id you get from order object.     
//    echo $country = $address->getCountry();
    $currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
    $currency_symbol = Mage::app()->getLocale()->currency($currency_code)->getSymbol();
    ?>
    <form method="post"  id="paymentform" action="<?php echo Mage::getBaseUrl(); ?>membership/payment/authorizepayment/" >
        <div class="form-list">
            <input type="hidden" value="<?php echo $customer_email; ?>" name="emailid" id="emailid" />  
            <input type="hidden" value="<?php echo $customer_custtele; ?>" name="custelephone" id="telephonenum" />  
            <input type="hidden" value="<?php echo $cust_id; ?>" name="cust_id" id="cust_id" />  
            <?php
            $region_id = $address->getRegionId();
            if ($region_id == '43') {
                $request = $taxCalculation->getRateRequest($address, null, null);
                $taxClassId = 2;
                $taxRate = $taxCalculation->getRate($request->setProductClassId($taxClassId));
                $taxval = $taxRate / 100;
               $taxable_amount111 = $amount * $taxval;
             $taxable_amount = number_format($taxable_amount111, 2);
                $mem_amount111 = $amount + $taxable_amount;
                 $mem_amount= number_format($mem_amount111, 2)
                ?>

                <input type="hidden" value="<?php echo $taxRate; ?>" name="tax_rate" id="tax" />        
                <input type="hidden" value="<?php echo $taxval; ?>" name="tax_rate_val" id="tax_rate_val" />        
            <?php }else {
                 $taxable_amount = 0;
                $mem_amount111 = $amount + $taxable_amount;
                 $mem_amount= number_format($mem_amount111, 2);
            } 
           
            if ((empty($mem_id)) && ($group_id === '15')) {
                ?>
                <div id="previous_membership">
                    <h3><?php echo $this->__('You Chose'); ?></h3><br>
                    <label>Membership</label>:<?php echo "Guest"; ?><br>
                    <label>Membership Amount</label>: <?php
                    echo $currency_symbol . $this->__('0')
                    ?>                                                      
                </div>


                <li class="fields">
                    <div class="field">
                        <label for="membership_plan" class="required"><?php echo $this->__('Choose your membership type') ?><em>*</em></label>
                        <div class="input-box">
                            <?php
                            $collection = Mage::getModel('membership/types')->getCollection()
                                    ->setOrder('oder', 'ASC')
                                    ->addFieldToFilter('status', '1')
                            ;
                            foreach ($collection as $types) {
                                $id_m = $types->getId();
                                $options = Mage::getModel('membership/types')->load($id_m);
                                ?>
                                <input type="radio" name="mem_type" value="<?php echo $options->getMembershipId(); ?>" onclick="javascript:GetPrice(this.value);" />&nbsp;<?php echo $options->getMembershipType(); ?><br>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="field">
                        <label for="membership_plan" class="required"><?php echo $this->__('Membership price') ?></label>

                        <div class="input-box" style="font-size: 15px;">


                            <div id="price_change" style="float: left;">
                                <?php echo $this->__('0') ?> <!-- amount here -->
                            </div>    
                            <input type="hidden" name="amt" id="mem_amt" value=" <?php echo $this->__('0') ?>"/>
  <input type="hidden" name="mem_type" id="mem_type" value="<?php echo $this->__('Guest') ?>" />
   <input type="hidden" name="mem_table_id" value="<?php echo $mem_id; ?>" />
    <input type="hidden" id="mem_table_id" name="mem_table_id" value="<?php echo $this->__('') ?>" />
                        </div>
                    </div>
                </li>
                <li>
                    <?php if($taxRate !=''){ ?>
                    <label>Tax</label>:<?php echo $currency_symbol ?><label id="amt123" for="mem_amt123" ><?php echo $this->__('0') ?></label><br>                   
                    <label>Amount to be paid</label>:<?php echo $currency_symbol ?><label id="amountpaid" for="amountpaid" ><?php echo $this->__('0') ?></label><br>                   
                    <?php }?>
                </li>



            <?php } else if (!empty($mem_id) && ($group_id === '15')) { ?>    
                <div id="previous_membership">
                    <h3><?php echo $this->__('You Chose'); ?></h3>
                    <label>Membership</label>:<?php echo $membership['membership_type']; ?>                   
                    <label>Membership Amount</label>: <?php echo $currency_symbol . $membership['membership_price']; ?>

                </div>           
                <li class="fields">
                    <div class="field">
                        <label for="membership_plan" class="required"><?php echo $this->__('Choose your membership type') ?><em>*</em></label>
                        <div class="input-box">


                            <?php
                            $model = Mage::getModel('membership/types');
                            $data = $model->getCollection()->getData();
                            foreach ($data as $options) {
                                ?>
                                <input type="radio" name="mem_type" value="<?php echo $options['membership_id']; ?>" onclick="javascript:GetPrice(this.value);" />&nbsp;<?php echo $options['membership_type']; ?><br>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="field">
                        <label for="membership_plan" class="required"><?php echo $this->__('Membership price') ?></label>

                        <div class="input-box" style="font-size: 15px;">
                            <?php echo "&nbsp; " . Mage::app()->getStore()->getCurrentCurrencyCode(); ?>

                            <div id="price_change" style="float: left;">
                                <?php echo $membership['membership_price'] ?> <!-- amount here -->
                            </div>    
                            <input type="hidden" name="amt" id="mem_amt" value=" <?php echo $this->__('0') ?>"/>
                            <input type="hidden" id="mem_type" name="mem_type" value="<?php echo $this->__('Guest') ?>" />
                         <input type="hidden" id="mem_table_id" name="mem_table_id" value="<?php echo $this->__('') ?>" />
                        </div>
                    </div>


                </li>
                <li>
                      <?php if($taxRate !=''){ ?>
                    <label>Tax</label>:<?php echo $currency_symbol ?><label id="amt123" for="mem_amt123" ><?php echo $this->__('0') ?></label><br>                   
                    <label>Amount to be paid</label>:<?php echo $currency_symbol ?><label id="amountpaid" for="amountpaid" ><?php echo $this->__('0') ?></label><br>                   
                      <?php }?>
                </li>

            <?php } else if (!empty($mem_id) && ($group_id !== '15')) { ?>
                <input type="hidden" name="mem_type" value="<?php echo $membership['membership_type']; ?>" />
                <input type="hidden" name="amt" value="<?php echo $amount; ?>" />
                <input type="hidden" name="mem_table_id" value="<?php echo $mem_id; ?>" />

                <div id="previous_membership">
                    <li>
                        <h3><?php echo $this->__('You Chose'); ?></h3><br>
                        <label>Membership</label>:<?php echo $membership['membership_type']; ?><br>
                        <label>Membership Amount</label>:  <?php echo $currency_symbol . $membership['membership_price']; ?><br>
                        <label>Tax</label>:<?php echo $currency_symbol . $taxable_amount ?> <br>         
                        <label>Amount to be paid</label>:<?php echo $currency_symbol . $mem_amount; ?>
                    </li>
                </div>
            <?php } ?>


            <div>
                <label for="card_number">Credit Card Number</label>  <i>(Visa, Amex and MasterCard currently accepted)</i>
                <div class="input-box">
                    <input type="text" class="input-text"  name="x_card_num" value=""></input>
                </div>
            </div>

            <div>       
                <label for="exp">Card Expiry date</label><br>

<!--                    <input type="text" class="input-text" size="4" name="x_exp_date" value=""></input>-->
                <select name="card_exp_year" style="width: 10%">
                    <?php
                    for ($ye = date("Y"); $ye <= date("Y") + 20; $ye++) {
                        echo "<option value='$ye'>$ye</option>";
                    }
                    ?> 

                </select> 

                <select name="card_exp_month" style="width:7%;">

                    <option value="01">01</option>
                    <option value="02">02</option>
                    <option value="03">03</option>
                    <option value="04">04</option>
                    <option value="05">05</option>
                    <option value="06">06</option>
                    <option value="07">07</option>
                    <option value="08">08</option>
                    <option value="09">09</option>
                    <?php
                    for ($mo = 10; $mo <= 12; $mo++)
                        echo "<option value='$mo'>$mo</option>";
                    ?>
                </select>

            </div>
            <div>
                <label for="CVV">CVV</label>
                <div class="input-box">
                    <input type="text" class="input-text" size="4" name="x_card_code" value=""></input>
                </div>
            </div>


            <div class="fields">
                <div class="field">
                    <label for="First Name">First Name</label>
                    <div class="input-box">
                        <?php
                        if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                            ?>
                            <input type="text" class="input-text" size="15" name="x_first_name" value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getFirstname(); ?>" readonly></input>
                        <?php } else { ?>
                            <input type="text" class="input-text" size="15" name="x_first_name" value="<?php echo Mage::getSingleton('customer/session')->getMemFname(); ?>" readonly></input>
                        <?php }
                        ?>
                    </div>
                </div>
                <div class="field">
                    <label for="Last Name">Last Name</label>

                    <div class="input-box">
                        <?php
                        if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                            ?>
                            <input type="text" class="input-text" size="14" name="x_last_name" value="<?php echo Mage::getSingleton('customer/session')->getCustomer()->getLastname(); ?>" readonly></input>
                        <?php } else { ?>
                            <input type="text" class="input-text" size="14" name="x_last_name" value="<?php echo Mage::getSingleton('customer/session')->getMemLname(); ?>" readonly></input>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="fields">
                <div class="field">
                    <p class="verify"><i>*Please click the link below to verify you have read the Terms and Conditions</i></p>
                    <label for="termservices" class="required pull-left">
                        <u class="show terms-cont" onclick="SubmitRequest();">Terms and Conditions</u>   <input type="hidden" required  value="" name="terms" id="termstext" />                                          
                    </label>
                    <!--neenu-->    

                </div>                           
                <div class="popupWrapper">
                    <div class="popupBox-1" id="popupBox">
                    </div>                         
                </div> 
            </div>
        </div>

        <div class="buttons-set">

            <button type="submit" onclick="checkForm()" title="Submit" class="button"><span><span>Submit</span></span></button>
        </div>
    </form>






</div>

<script>
    var jqCustom = jQuery.noConflict();
    function termsSelect() {
        //termservices
        if (jqCustom("#termservices").prop('checked') === true)
        {
            jqCustom("#termstext").val('1');//insert 1
        } else
        {
            jqCustom("#termstext").val(''); //insert '';
        }
    }

    function checkForm()
    {
        jqCustom('#paymentform').submit(function (e) {
            // DO STUFF
            // return false to cancel form action

            var checkboxdata = jqCustom("#termstext").val();
            if (!checkboxdata) {
                alert("Please read the Terms and Conditions");
                e.preventDefault();
                return false;
            } else {
                return true;
            }
        });
    }
    jqCustom(".show").click(function () {
        jqCustom(".popupWrapper").fadeIn();
    });

    function SubmitRequest()
    {
        //                            var passvrb= val;         // sent value '1' for link click check                 
        //  $('termstext').writeAttribute('value', passvrb);// change text box value 
        new Ajax.Request('<?php echo Mage::getUrl("mycloset/termservices", array( '_secure' => true))   ?>',
                {
                    method: "get",
                    onSuccess: function (transport) {
                        var response = transport.responseText || "no response text";
                        //cashorcard_webnmobile_apikey
                        node = $("popupBox");
                        node.update(response);
                    },
                    onFailure: function () {
                        node = $("popupBox");
                        node.update('');
                    }
                });

    }
    function GetPrice(memid)
    {
        $('previous_membership').hide();

        new Ajax.Request('<?php echo Mage::getUrl('',array('_secure' => true)) . "membership/payment/Getprice?memid=" ?>' + memid,
                {
                    method: "get",
                    onSuccess: function (transport) {
                        var response = transport.responseText || "no response text";
                        node = $("price_change");
                        var res = response.split("@");                    
                        var details = res[0];
                        node.update(details);

                        var amt = res[1];
                        var mem_type = res[2];
                        var mem_table_id = res[3];
                       
                        $('mem_amt').writeAttribute('value', amt);
                        $('mem_type').writeAttribute('value', mem_type);
                        $('mem_table_id').writeAttribute('value', mem_table_id);
                        var tax_val = $$('[name="tax_rate_val"]')[0].value;
                        var tax_paid = parseFloat(amt) * parseFloat(tax_val);
                        var tax_paid1 = tax_paid.toFixed(2);
//                        var tax_paid1 =Math.round(tax_paid);

                        $$('label[id="amt123"]').first().update(tax_paid1);

                        var amount_paid1 = parseFloat(amt) + parseFloat(tax_paid);
                        var amount_paid = amount_paid1.toFixed(2);
                        $$('label[id="amountpaid"]').first().update(amount_paid);

                    },
                    onFailure: function () {
                        alert("Something went wrong...")
                    }
                });


    }

</script>








<div class="buttons-set">
    <p class="back-link"><a onclick="goBack()" class="back-link"><small>&laquo;Back</small></a></p>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>