<?php
$p = $this->getProductdetails();
//echo $p['qty'];exit;
$rel_product = $p['rel_id'];
$model = Mage::getModel('catalog/product')->load($rel_product);


$prefix = Mage::getConfig()->getTablePrefix();
$user_id = Mage::getSingleton('customer/session')->getId(); // login user id
$userid = ($user_id ? $user_id : 0);
$cat = Mage::getModel('catalog/category')->load(16);
$subcats = $cat->getChildren();
$all_sub_cat = explode(',', $subcats);
$product = $p['id'];
//currebt product id
$cats = $product->getCategoryIds();
foreach ($cats as $category_id) {
    $_cat = Mage::getModel('catalog/category')->load($category_id);
    $catname = $_cat->getName();
    $catid = $_cat->getId();
    $category = Mage::getModel('catalog/category')->load($catid);

    $caid = array();
    foreach ($category->getParentCategories() as $parent) {
        $caid[] = $parent->getId();
    }
}


if (in_array('9', $caid)) {

    $_product = Mage::getModel('catalog/product')->load($rel_product);
    ?>

    <div class="popupHead">
        <div class="sku dress-code hidden-xs"> <?php echo $p['sku']; ?></div>
        <a class="close" style="float: right;">X</a>
    </div>
    <div class="popupContent">
        <div class="row productdata" id="productdata">
            <div class="catname col-sm-12 visible-xs center-align">
                <h2><?php echo $catname; ?></h2>

            </div>
            <div class="col-sm-7 image " style="min-height: 200px;">
                <img alt="" src="<?php echo $p['ImageUrl']; ?>"/>                                                                                
            </div>
            <div class="col-sm-5 details">
                <!--category name-->
                <h2 class="catname hidden-xs"><?php echo $catname; ?></h2>

                <!--ShortDescription-->
                <p class="description">
                    <?php echo $p['ShortDescription']; ?>
                </p>

            
                        <div class="add-to-cart">
                            <label class="qty_lbl" for="qty"><?php echo $this->__('Qty:') ?></label>
                            <input type="text" name="qty" id="qty" maxlength="3" value="" title="<?php echo $this->__('Qty') ?>" class="input-text qty_countbox" />
                            
                        </div>                                                  
                <div class="add_tobag">
                <button title="<?php echo $this->__('ADD TO BAG') ?>" class="button btn-cart" onclick="updateLocation('<?php echo $this->getAddToCartUrl($product) ?>','<?php echo $product->getId(); ?>')" ><?php echo $this->__('ADD TO BAG') ?></button>
                </div>
            </div>
        </div>
    </div>


<?php } else { ?>

    <div class="popupHead">
        <div class="sku dress-code hidden-xs"> <?php echo $p['sku']; ?></div>
        <a class="close" style="float: right;">X</a>
    </div>
    <div class="popupContent">
        <div class="row productdata" id="productdata">
            <div class="catname col-sm-12 visible-xs center-align">
                <h2><?php echo $catname; ?></h2>
                <p class="signature visible-xs" style="font-style: normal;"><?php echo $p['designer']; ?></p>
            </div>
            <div class="col-sm-7 image " style="min-height: 200px;">
                <img alt="" src="<?php echo $p['ImageUrl']; ?>"/>                                                                                
            </div>
            <div class="col-sm-5 details">
                <!--category name-->
                <h2 class="catname hidden-xs"><?php echo $catname; ?></h2>
                <p class="visible-xs productId"> <b>Product ID</b>: <?php echo $p['sku']; ?></p>
                <p class="signature hidden-xs"><?php echo $p['designer']; ?></p>
                <div class="colorBox">
                    <a style=" background:<?php echo $p['color']; ?>"></a>
                </div>
                <div class="size"><b>Size:</b> <i> <?php echo $p['size']; ?></i></div>


                <!--season details-->
                <div class="season_multiselect" style="display:inline-block; vertical-align:top; overflow:hidden;font-style: normal; "> <b>Seasons</b></br>
                    <div class="preselect"> <select  attrproduct="<?php echo $rel_product; ?>" id="season" class="season123"  multiple="multiple" size="4" name="product[season][]">
                            <?php
                            foreach ($p['season'] as $key => $value) {
                                ?> 
                                <option 
                                <?php if (in_array($value['label'], $p['season_select'])) { ?>
                                        selected="selected" style="color:#010101; background:#ededed;"  
                                    <?php } ?>
                                    value="<?php echo $value['value'] ?>"><?php echo $value['label'] ?>
                                </option>
                            <?php } ?>
                        </select></div>
                </div>

                <!--  tag details   -->
                <div class="tags">
                    <b >Tags: </b>
                    <div class="tagappend">
                        <?php
                        foreach ($p['tag_select'] as $option_label) {
                            foreach ($option_label as $labelid) {
                                ?>
                                <span class="tagitem" id="tagitem">
                                    <a><?php echo $labelid; ?></a>
                                    <i class="tagclose" pro="<?php echo $rel_product; ?>" tagval="<?php echo $labelid; ?>">x</i>                             
                                </span> 
                                <?php
                            }
                        }
                        ?>
                        <span id="remove" class="add add-text"><input type="text" class="inputz" pro="<?php echo $rel_product; ?>" name="tagss" value=""></span>       
                        <span id="remove pluse" class="tagpluse"><i class='tagadd'>+</i></span> 
                    </div>
                </div>



                <!--ShortDescription-->
    <!--            <p class="description">
                <?php //echo $p['ShortDescription'];  ?>
                </p>-->
                <p class="status">
                   <?php  if ($p['product_status']== 'Shipped To') { $shipped_to = $p['shipped_to']; }else { $shipped_to = '';} ?>
                    <b>Status:</b> <?php echo $p['product_status'] . ' ' . $shipped_to ?>
                </p>
                <!--product_status-->
                <?php
                if ($userid) {
                    if ($p['product_status'] == 'We Have It') {
                        ?>
                        <button type="button" title="<?php echo $this->__('Deliver Me') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')"><span><span><?php echo $this->__('Deliver Me') ?></span></span></button>
                    <?php } else { ?>
                        <button title="<?php echo $this->__('Pick Me Up') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($product) ?>')" ><?php echo $this->__('Pick Me Up') ?></button>
                        <?php
                    }
                } else {
                    if ($p['product_status'] == 'We Have It') {
                        ?>
                        <a  title="<?php echo $this->__('Deliver Me') ?>" class="button btn-cart" href="<?php echo $this->getUrl('', array('_secure' => true)) ?>membership/account/create/"><span><span><?php echo $this->__('Deliver Me') ?></span></span></a>
                    <?php } else { ?>
                        <a title="<?php echo $this->__('Pick Me Up') ?>" class="button btn-cart" href="<?php echo $this->getUrl('', array('_secure' => true)) ?>membership/account/create/"><?php echo $this->__('Pick Me Up') ?></a>  
                        <?php
                    }
                }
                ?> 
            </div>
        </div>
        <!--SHOW BY-->
        <div>
            <div class="customDropDown pull-left show_category">
                <div class="dropContentBox">
                    <b>SHOW</b>
                    <ul>
                        <li> <b>Category</b>
                            <ul id="showdrop" style="display:block;">  
                                <li class="selected" > <a class="getcatid" rel="16" >All Categories</a></li>
                                <?php
                                foreach ($all_sub_cat as $cat_id) {
                                    $category = Mage::getModel('catalog/category')->load($cat_id);
                                    $categories = Mage::getModel('catalog/category')->load($category->getId())
                                            ->getProductCollection()
                                            ->addAttributeToSelect('entity_id')
                                            ->addAttributeToFilter('status', 1)
                                            ->addAttributeToFilter('visibility', 4);
                                    $products = Mage::getModel('catalog/product')
                                            ->getCollection()
                                            ->addAttributeToFilter('customer_id', $userid)
                                            ->addCategoryFilter($category)
                                            ->load();

                                    if (($products->count() > 0 ) && ($userid)) {
                                        ?>              
                                        <li >                       
                                            <a class="getcatid" rel="<?php echo $category->getId(); ?>" > <?php echo ucfirst(strtolower($category->name));  ?></a> 
                                        </li>    

                                    <?php } else if (($categories->count() > 0) && (!$userid)) {
                                        ?>
                                        <li >                       
                                            <a class="getcatid" rel="<?php echo $category->getId(); ?>" > <?php echo ucfirst(strtolower($category->name)); ?></a> 
                                        </li> 
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </li>
                    </ul>
                    <span>Category</span>
                </div>
            </div>
        </div>
        <!--slider-->
        <div class="flexsliderPopup flexslider carousel">
            <ul class="slides">
                <?php
                foreach ($all_sub_cat as $cat_id) {
                    $category = Mage::getModel('catalog/category')->load($cat_id);
                    $categories = Mage::getModel('catalog/category')->load($category->getId())
                            ->getProductCollection()
                            ->addAttributeToSelect('entity_id')
                            ->addAttributeToFilter('status', 1)
                            ->addAttributeToFilter('visibility', 4);
                    $products = Mage::getModel('catalog/product')
                            ->getCollection()
                            ->addAttributeToFilter('customer_id', $userid)
                            ->addCategoryFilter($category)
                            ->load();
                    if ($products->count() > 0) {
                        ?>              
                        <li >                       
                            <a class="getcatid" rel="<?php echo $category->getId(); ?>" ><img  src="<?php echo Mage::getBaseUrl('media') . 'catalog/category/' . $category->image; ?>" alt=""/><p><?php echo $category->name; ?></p></a> 
                        </li>    
                        <?php
                    }
                }
                ?>
            </ul>
        </div>

    </div>
<?php } ?>
<script type="text/javascript">
    var jqCustom = jQuery.noConflict();
    jqCustom(document).ready(function () {
        var jqCustoms = jQuery.noConflict();
        //var jqCustom = jQuery.noConflict();
        //slider change images of product
        jqCustoms('.getcatid').click(function () {
            var jqCustom = jQuery.noConflict();
            var catid = jqCustom(this).attr('rel');
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/slider",
                type: 'post',
                data: {
                    categoryId: catid
                },
                success: function (data) {
                    jqCustom('.flexsliderPopup').remove();
                    jqCustom(data).appendTo(".popupContent");

                }
            });
        });


        //        showby started here        
        //        designer 

        jqCustoms('.getdesignerid').click(function () {
            var jqCustom = jQuery.noConflict();
            var productid = jqCustom(this).attr('relpro');
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/productdesigner",
                type: 'post',
                data: {
                    ProductIds: productid
                },
                success: function (data) {
                    jqCustom('.flexsliderPopup').remove();
                    jqCustom(data).appendTo(".popupContent");

                }
            });
        });
        //        color
        jqCustoms('.getcolorid').click(function () {
            var jqCustom = jQuery.noConflict();
            var productid = jqCustom(this).attr('relcolor');
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/productcolor",
                type: 'post',
                data: {
                    ProductIds: productid
                },
                success: function (data) {
                    jqCustom('.flexsliderPopup').remove();
                    jqCustom(data).appendTo(".popupContent");

                }
            });
        });

 //getproduct_statusid
        jqCustoms('.getproduct_statusid').click(function () {
            var jqCustom = jQuery.noConflict();
            var productid = jqCustom(this).attr('relproduct_status');
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/productstatus",
                type: 'post',
                data: {
                    ProductIds: productid
                },
                success: function (data) {
                    jqCustom('.flexsliderPopup').remove();
                    jqCustom(data).appendTo(".popupContent");

                }
            });
        });
        //getseasonid
        jqCustoms('.getseasonid').click(function () {
            var jqCustom = jQuery.noConflict();
            var productid = jqCustom(this).attr('relseason');
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/season",
                type: 'post',
                data: {
                    ProductIds: productid
                },
                success: function (data) {
                    jqCustom('.flexsliderPopup').remove();
                    jqCustom(data).appendTo(".popupContent");

                }
            });
        });

        var footHeight = jqCustoms("footer").outerHeight();
        jqCustoms(".footFix").css({"paddingBottom": footHeight + "px"});
        jqCustoms("header .loginDetails span").click(function () {
            jqCustom("header .loginDetails .links").fadeToggle(function () {
                jqCustom("header .loginDetails .search").fadeToggle();
            });
        });

//To check
    /*  jqCustoms(".small-accordion h4").click(function () {
        alert('lllllllllll');
         var jqCustom = jQuery.noConflict();
            if (jqCustom(this).next("div").css('display') == 'none')
            {
                jqCustom(".small-accordion > div").slideUp();
                jqCustom(this).next("div").slideDown();
            }
            else
            {
                jqCustom(this).next("div").slideUp();
            }
        });

*/
  
        jqCustoms(document).click(function () {
            var jqCustom = jQuery.noConflict();
                jqCustom(".customDropDown ul").slideUp(100);
                
        });

        jqCustoms(".customDropDown").click(function (event) {

              var jqCustom = jQuery.noConflict();
            jqCustom("#showdrop").css('display','block')
            if (jqCustom(this).children().children("ul").css('display') == 'none')
            {
                var getPosition = jqCustom(this).children().children("b").width() + 20;

                jqCustom(this).children().children("ul").css({"left": getPosition + "px"}).slideDown();
            
            }
            event.stopPropagation();
        });
//        jqCustom(".customDropDown ul li > b").click(function () {
//            alert('2222');
//            if (jqCustom(this).next("ul").is(":visible"))
//            {
//                jqCustom(this).next("ul").slideUp();
//            }
//            else
//            {
//                jqCustom(".customDropDown ul li > ul").slideUp();
//                jqCustom(this).siblings("ul").slideDown();
//            }
//        })
  jqCustoms(".customDropDown ul li ul li").click(function (event) {
            var jqCustom = jQuery.noConflict();
            jqCustom(".customDropDown ul li ul li.selected").removeClass("selected");
            var thisHtml = jqCustom(this).html();
            var jqCustom = jQuery.noConflict();

         //   jqCustom(".customDropDown ul").fadeOut(100);
            jqCustom(this).addClass("selected").parents("ul").siblings("span").html(thisHtml);
               event.stopPropagation();
        });


        jqCustoms('.inputz').blur(function (e) {
            var jqCustom = jQuery.noConflict();
            var tag = jqCustom('.inputz').val();

            if (tag != null && tag != '') {
                var productid = jqCustom(this).attr('pro');
                jqCustom.ajax({
                    url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/inserttag",
                    type: 'post',
                    data: {
                        tag: tag,
                        productid: productid
                    },
                    success: function (data1) {
                        var data = parseInt(data1);
                        var tagname = jqCustom('.inputz').val();
                        if (tagname != null) {
                            jqCustom("<span>" + jqCustom('.inputz').val() + "<i class='tagclose' tagval='" + data + "' >x</i></span>").prependTo(".tags > div");
                            jqCustom("input.inputz").val('');
                            jqCustom(".tagclose").on("click", function () {
                                var productid = jqCustom(this).attr("pro");
                                var tag1233 = jqCustom(this).attr("tagval");
                                jqCustom.ajax({
                                    url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/deletetag",
                                    type: 'post',
                                    data: {
                                        tag: tag1233,
                                        productid: productid
                                    },
                                    success: function () {
                                    }
                                });
                                jqCustom(this).parent('span').remove();
                            });
                        }
                    }
                });
            }
        });

      jqCustoms(".tagclose").on("click", function () {
            var jqCustom = jQuery.noConflict();
            var tag123 = jqCustom(this).attr("tagval");
            var productid = jqCustom(this).attr("pro");
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/deletetag",
                type: 'post',
                data: {
                    tag: tag123,
                    productid: productid
                },
                success: function () {
                }
            });
            jqCustom(this).parent('span').remove();
        });
        jqCustoms(".tagadd").on("click", function () {
             var jqCustom = jQuery.noConflict();
            jqCustom(".add-text").show();
            jqCustom(".tagpluse").hide();
        });
        jqCustoms(".close,.popClose").click(function () {
             var jqCustom = jQuery.noConflict();
            jqCustom(".popupWrapper").fadeOut();
            jqCustom(".popupBox").empty();
        });

        jqCustoms("select").blur(function () {
            var jqCustom = jQuery.noConflict();
            var seasonnames = new Array();
            var i = 0;
            var productid = jqCustom(this).attr('attrproduct');
            jqCustom("select option:selected").each(function () {
                seasonnames[i] = jqCustom(this).val();

                i++;

            });
            jqCustom.ajax({
                url: "<?php echo Mage::getBaseUrl(); ?>" + "mycloset/popup/seasoninsert",
                type: 'post',
                data: {
                    seasonnames: seasonnames,
                    productid: productid
                },
                success: function () {
                }
            });
        });












});
















    var jqCustom = jQuery.noConflict();
    jqCustom(window).load(function () {
        var jqCustom = jQuery.noConflict();
        jqCustom('.flexslider').flexslider({
            animation: "slide",
            animationLoop: false,
            itemWidth: 350,
            itemMargin: 5
        });
    });
    setTimeout(function () {
        jqCustom('.flexsliderPopup').flexslider({
            animation: "slide",
            animationLoop: false,
            itemWidth: 150,
            itemMargin: 5
        });
    }, 100);
    jqCustom(".season select option:not(:checked)").css("color", "black");
    var jqCustom = jQuery.noConflict();
</script>