<?php
/**
 * Ultimate_creditcard extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Ultimate
 * @package        Ultimate_creditcard
 * @copyright      Copyright (c) 2015
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Customer view widget template
 *
 * @category    Ultimate
 * @package     Ultimate_creditcard
 * @author      Ultimate Module Creator
 */
?>
<?php $_customer = $this->getCurrentCustomer();?>
<?php if ($_customer) :?>
    <div class="customer-widget-view">
        <h3><?php echo $_customer->getCreditcardNumber()?></h3>
        <div>
            <div class="creditcard_number-widget">
                <?php echo Mage::helper('ultimate_creditcard')->__('creditcard number');?>:<?php echo $_customer->getCreditcardNumber();?>
            </div>
            <div class="creditcard_exp-widget">
                <?php echo Mage::helper('ultimate_creditcard')->__("Exp_Date");?>: <?php echo Mage::helper('core')->formatDate($_customer->getCreditcardExp(), 'full');?>
            </div>

        </div>
    </div>
<?php endif;?>
