<form id="co-pickup-form" action="">
<fieldset>
    <ul class="form-list">
    <li id="pickup-form">
        <fieldset>
            <ul>
                <li class="wide">
                    <label for="pickup:like" class="required"><em>*</em><?php echo $this->__('Do you like this post?') ?></label>
                    <div class="input-box">
                        <input type='text' name='pickup[like]'  class="required-entry input-text" id="pickup:like" value='<?php echo $this->getQuote()->getExcellenceLike2()?>'/>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="pickup-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="pickup.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="pickup-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var pickup = new ExcellenceMethod2('co-pickup-form','<?php echo $this->getUrl('custom/onepage/saveExcellence2') ?>');
    var excellenceForm2 = new VarienForm('co-pickup-form');
//]]>
</script>
